### ISSUE TITLE
ZBM hook is called before USB storages get loaded

### ISSUE THREAD

**Issue by solbjorn** [zbm-dev/zfsbootmenu#182] opened 2021-06-20 21:19 UTC
Pre-compiled ZBM 1.9.0 as separate vmlinuz + initramfs, booted via systemd-boot.

ZBM doesn't find my pools stored on USB-HDD. `loglevel=7` shows that ZBM hook starts searching for pools (and ends up failing) BEFORE USB storage drivers come in and probe USB-HDD. As a result, I get emergency shell in which I can successfully import and manage pools.

I think this could be worked around using `zbm.import_retries`, but it isn't present in any stable release yet. However, this issue is not of "just w/a it" type to me as ZBM might miss lots of storage devices that way.

Sorry for the photo instead of logs, dunno how to capture them from such a preboot environment (this is a part of dmesg output).

![IMG_20210620_235515](https://user-images.githubusercontent.com/12006295/122689574-e99cfc80-d223-11eb-9e09-a7674a5ccf6c.jpg)

Also, I saw `udevadm settle` in ZBM scripts, have no idea why it does report that udev is done with the devices.

**Comment by ahesford** [comment] 2021-06-21 00:04
Unfortunately, there is not a lot we can do besides the import-retry workaround. The issue is knowing when to stop waiting. With import retry, we prefer a pool specified by `zbm.prefer` exactly once; after that, all bets are off and the first importable pool will terminate the retry loop. I worry that changing this behavior dramatically would help in a few very specific cases but hurt the "we try our best to find *something* bootable" mentality, which is probably the preferred mode when something goes wrong with your preferred pool. This starts to look more like recover than normal operation.

One possibility would be to include a specialized setup hook that can implement the specific logic you want to ensure that a particular USB pool is always ready. See, for example, the demo hook at https://github.com/zbm-dev/zfsbootmenu/blob/master/contrib/keycache.sh for some inspiration.

**Comment by solbjorn** [comment] 2021-06-21 08:46
I have only one pool so import-retry should work for me. I'll let know (and close this if it will) once prebuilt 1.9.1 is released.

**Comment by solbjorn** [comment] 2021-06-21 10:55
@ahesford, maybe consider adding a cmdline parameter like `zbm.delay` or `zbm.startup_delay` in seconds that would take place prior to running main ZBM logics? 1 sec would be enough for my storages to become ready.

**Comment by ahesford** [comment] 2021-06-21 14:20
Dracut has several different hook stages, all described in [`dracut.modules(7)`](https://man.voidlinux.org/dracut.modules.7). ZBM injects a `cmdline` hook to parse the kernel command-line, and then adds a `pre-mount` hook that execs the core ZBM runtime and effectively ends dracut's control of the boot process. If you really want to do this the right way, it would take a custom dracut module that you could install as `pre-trigger` or `initqueue/finished` to ensure that the devices you need are available before allowing ZBM to start up. (Note: dracut defines several "main loop" iniqueue hooks, but *none* are ever guaranteed to run except `initqueue/finished`. The other hooks are only run if dracut determines that it has *not* finished.)

Thinking more about your problem, I realize that our current "setup" hook system isn't really suitable, because those hooks run too late. Our setup hooks are intended to be run after everything is imported and available, as a last-ditch attempt to configure things before the menu will launch. I could be persuaded to add another stage of setup hooks (maybe "initialize" hooks) which could run in `zfsbootmenu-init.sh` before it attempts to import any pools; this would provide a place to busy-wait for the devices you need on your own terms. Effectively this would recreate the dracut hooks that you can already inject, but eliminates some development overhead by not requiring that you implement your own dracut module.

**Comment by zdykstra** [comment] 2021-06-30 15:27
https://github.com/zbm-dev/zfsbootmenu/commit/e2caa8143acf373b16fa91082fef68b78fa0dbd4 has been developed to help with this issue. It will be part of ZFSBootMenu 1.10.0, which will be tagged very soon. If you're interested in testing this change, I can provide a signed EFI built from what will be the 1.10.0 release code.

**Comment by solbjorn** [comment] 2021-06-30 19:55
@zdykstra, thanks! Feel free to do that, I'd be very glad to test!

**Comment by zdykstra** [comment] 2021-07-01 04:58
GitHub won't let me upload any files/archives to this issue for some reason. The files can be downloaded from [here](https://pastebin.stratumzero.date/u/p/6ff314796d/1.10.0.tar.gz). You'll just want to add `zbm.prefer=yourpool!` to the ZBM command line via rEFInd, efibootmgr or however else you boot it. Please let me know if you run into any issues with this release - it should hopefully accomplish what you need!

**Comment by solbjorn** [comment] 2021-07-01 14:03
I confirm that now ZBM imports my pools from USB-HDD just fine, on the second automatic retry. I don't even have to specify the preferred pool (since I have only one, and it has bootfs property set).
I get a warning about unsupported features since I use ZFS 2.1.0-rc8, but that's fine. I'm able to get to the boot menu itself, and it determines both my active BE and kernel correctly.

So this issue is resolved, thanks!

_(the following is not related to this particular issue)_

However, when it runs the OS itself, I get a kernel error that it's unable to run /sbin/init ("_/sbin/init found, but cannot be run: error -95_")
The contents of my /boot folder is following (Arch Linux):

```
-rw-r--r-- 1 root root 32071096 Jun 30 19:46 initramfs-linux-xanmod-cacule-fallback.img
-rw-r--r-- 1 root root 13394075 Jun 30 19:46 initramfs-linux-xanmod-cacule.img
-rw-r--r-- 1 root root  4769792 Jun  8 20:31 intel-ucode.img
-rw-r--r-- 1 root root 11996576 Jun 30 19:46 vmlinuz-linux-xanmod-cacule
```

ZBM determines the corresponding initramfs correctly, according to its working files, so dunno what happens.
Can this be related to that I'm booting from USB-HDD and ZBM performs USB teardown prior to booting the OS?

**Comment by zdykstra** [comment] 2021-07-01 14:21
No, the tear down hooks are executed after both the kernel and initramfs have been loaded into memory. I don't know a lot about `mkinitcpio` - maybe @ahesford has an idea on it.

**Comment by ahesford** [comment] 2021-07-01 14:32
My first suspicion is that something went wrong with the mkinitcpio run and the initramfs is invalid.

**Comment by solbjorn** [comment] 2021-07-01 14:40
Yeah, but if I boot the system with this initramfs directly from systemd-boot, there are no errors, all is working.

**Comment by ahesford** [comment] 2021-07-01 14:52
Are you sure the initramfs on /boot in your BE is identical to the version on the ESP that you are booting with systemd-boot?

**Comment by solbjorn** [comment] 2021-07-01 15:13
Yep, I copied them right before trying to boot via ZBM. I'll try to collect any possible additional info on that later.

Also, should I proceed here or it's better to create a new issue and close this as completed?

**Comment by zdykstra** [comment] 2021-07-01 15:21
I'd say make a new issue with a relevant issue title - it'll hopefully be easier to locate when people search for that specific problem.

**Closed** 2021-07-01 15:24 UTC
