### ISSUE TITLE
/etc/profile not sourced

### ISSUE THREAD

**Issue by Sithuk** [zbm-dev/zfsbootmenu#241] opened 2022-01-01 13:01 UTC
I've been testing updates to the ubuntu zfsbootmenu install script and noticed that the zfsbootmenu kernel/snapshot UI fails to launch. I get the following error following the rEFInd screen.
"WARNING: /etc/profile was not sourced; unable to proceed"
I am then presented with the "zfsbootmenu / >" prompt.

Zdykstra noted in a previous pull request that "/etc/profile" or "/lib/zfsbootmenu-lib.sh" is sourced by the shell.
https://github.com/zbm-dev/zfsbootmenu/pull/169

I've looked at recent commits and noticed that core library routines have been separated from main UI routines. Could that commit have caused an issue with sourcing "/lib/zfsbootmenu-lib.sh"?
https://github.com/zbm-dev/zfsbootmenu/commit/044df51857db3ad4f7e45be991114fb2e45a1dec

The ubuntu zfsbootmenu install script can be found at the following link for reference.
https://gitlab.com/Sithuk/ubuntu-server-zfsbootmenu/

**Comment by zdykstra** [comment] 2022-01-01 14:12
From the recovery shell, please run `cat /etc/profile` and `source /etc/profile`. If possible, please share a screen shot or a picture of what is shown on your screen after each/both.

**Comment by Sithuk** [comment] 2022-01-01 14:18
Screenshot attached
![Capture1](https://user-images.githubusercontent.com/48687737/147852614-dd807144-8e80-4ade-9126-e80a9b1ebcfa.JPG)
.

**Comment by zdykstra** [comment] 2022-01-01 14:23
Try `set -x ; source /etc/profile`  It'll probably spam a lot - but maybe it'll tell you where it stops/fails. Otherwise, run `set +x` (if you've run `set -x`) and then try to source each of the three files individually. One of those should fail - please let me know which one.

**Comment by Sithuk** [comment] 2022-01-01 14:44
![Capture2](https://user-images.githubusercontent.com/48687737/147853102-b055dccb-8b6a-4f1c-81d8-673d547233cc.JPG)
![Capture3](https://user-images.githubusercontent.com/48687737/147853104-bf8e9c4c-8c8c-424a-9d50-43e0d6b6ec34.JPG)

**Comment by ahesford** [comment] 2022-01-01 14:45
If the return code is nonzero after sourcing /etc/profile, that means it gets a nonzero return code from zdebug.

**Comment by ahesford** [comment] 2022-01-01 14:47
After review, this is expected behavior, because zdebug returns 1 when the log level doesn't match. We missed this in testing because we set loglevel=7 by default, I think.

The zdebug line in /etc/profile should be or'ed with true to suppress the nonzero exit and avoid triggering the UI failure.

**Comment by zdykstra** [comment] 2022-01-01 14:53
This should be fixed now - thank you for the bug report and the additional information!

**Closed** 2022-01-01 14:52 UTC

**Comment by Sithuk** [comment] 2022-01-01 15:25
I'm glad to help. Thank you for your and team's efforts on zfsbootmenu and for the fast response to fix the issue.
